name: Build ExternalHack

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Geode Mod
        id: build
        uses: geode-sdk/build-geode-mod@main

      - name: Upload ExternalHack
        uses: actions/upload-artifact@v4
        with:
          name: ExternalHack
          path: ${{ steps.build.outputs.build-output }}